# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mandril_key: B-np288rRL26UmIYFiM9Vg
  secret_key_base: d20fb45453dc0f0de59a151b255757aaf890072cb741db0bf9120e68f08811d8efda4acec0299a8c6299173b485b728d5ebfeff4aec140112374362904a0d6fb

test:
  mandril_key: B-np288rRL26UmIYFiM9Vg
  secret_key_base: c8c9199f5180fbe0001379bdc9ec35b80b233f27862532845a4a37206a27eaef5da2c378c386d0ed79831d4c96f53aa9f000af8c4f3ae9def629b0e686b33aee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mandril_key: B-np288rRL26UmIYFiM9Vg
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
